### ISSUE TITLE
Stuck when processing element hierarchy.

### ISSUE THREAD

**Issue by 52871299hzy** [ArMM1998/puyo_anim#1]
The script ran for several minutes without returning when processing cut_car_kime3.gncs from Wii version of Puyo Puyo 20th anniversary (0519.arc/cut_car_kime3.gncs). Terminating it with Ctrl-C gives this traceback:
```
Traceback (most recent call last):
  File "/home/bob/puyo_anim/puyo_anim.py", line 518, in <module>
    hierarchy = get_hierarchy(hierarchy_off, num_elem_in_bank)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bob/puyo_anim/puyo_anim.py", line 354, in get_hierarchy
    parenting = getParentData(hierarchy)
                ^^^^^^^^^^^^^^^^^^^^^^^^
[cut_car_kime3.zip](https://github.com/ArMM1998/puyo_anim/files/12715556/cut_car_kime3.zip)

  File "/home/bob/puyo_anim/puyo_anim.py", line -1, in getParentData
KeyboardInterrupt
```
[cut_car_kime3.zip](https://github.com/ArMM1998/puyo_anim/files/12715556/cut_car_kime3.zip)
Other animation files in the same archive works fine.

`--debug` gives this: [debug.log](https://github.com/ArMM1998/puyo_anim/files/12715798/debug.log)

**Comment by ArMM1998** [comment]
It seems the script is getting stuck going through the hierarchy of the element tree.
Looks like I might need to rework the function for it.

**Comment by ArMM1998** [comment]
It turns out the whole system is called "Left Child Right Sibling" and it's surprisingly less complicated than i thought lol.
[comitted a quick fix](https://github.com/ArMM1998/puyo_anim/commit/01cbe5a310db38ce9981ee79fc406330d859e2d1) where it doesn't get stuck anymore and should properly convert the file now.
